import { StyleSheet } from "react-native";
import { grayColor } from "../../style";

const styles = StyleSheet.create({
  sendButtonBg: {
    backgroundColor: grayColor,
    borderRadius: 50,
    padding: 10,
  },
  messageChatInput: {
    display: "flex",
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 4,
    paddingBottom: 2,
    marginTop: 2,
    width: "95%",
    marginLeft: "auto",
    marginRight: "auto",
  },
  inputContainer: {
    flexDirection: "row",
    flex: 1,
    alignItems: "center",
    padding: 2,
    borderRadius: 50,
    borderWidth: 1,
    borderColor: grayColor,
    width: "90%",
    alignSelf: "center",
    marginBottom: 0,
    padding: 5,
  },
  sendButtonAndLine: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    marginRight: 5,
  },
  //   messageChatInputBg: {},
  verticalLine: {
    height: 35,
    width: 1,
    backgroundColor: "#E5E6E9",
    marginRight: 10,
    marginLeft: 5,
  },
  chatBootMessageContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-start",
  },
  userMessageContainer: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "flex-end",
  },
  userMessageBg: {
    width: "auto",
    maxWidth: "70%",
    marginStart: 9,
    margin: 4,
  },
  chatBootMessageBg: {
    width: "auto",
    maxWidth: "70%",
    marginLeft: 12,
    margin: 2,
  },
  messageText: {
    color: "#FFF",
    fontSize: 15,
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: "400",
    letterSpacing: -0.3,
    padding: 10,
    paddingStart: 20,
    paddingEnd: 20,
    borderRadius: 40,
  },
  messageTime: {
    color: "#8A91A8",
    fontSize: 12,
    fontFamily: "Inter",
    fontStyle: "normal",
    fontWeight: "400",
  },
  // phoneCallSnackbar: {
  //   backgroundColor: "white",
  //   color: "black",
  //   borderTopLeftRadius: 20,
  //   borderTopRightRadius: 20,
  //   padding: 13,
  //   // shadowColor: "black",
  //   // shadowOffset: { width: 0, height: -4 },
  //   // shadowOpacity: 0.15,
  //   // shadowRadius: 20,
  // },
  // phoneCallSnackbarContainer: {
  //   backgroundColor: "white",
  //   display: "flex",
  //   gap: 15,
  // },
  // snackbarBackDismiss: {
  //   display: "flex",
  //   flexDirection: "row",
  //   justifyContent: "flex-end",
  //   alignItems: "center",
  //   // marginLeft: 270,
  //   // backgroundColor: "blue",
  // },
  // contactAiAgent: {
  //   color: "#1C81CB",
  //   fontSize: 17,
  //   fontFamily: "Manrope",
  //   fontStyle: "normal",
  //   fontWeight: "700",
  //   textTransform: "uppercase",
  //   textAlign: "center",
  //   marginLeft: 40,
  //   marginTop: 5,
  //   width: "100%",
  // },
  // phoneNumberText: {
  //   color: "#1E1E1E",
  //   fontSize: 17,
  //   fontFamily: "Manrope",
  //   fontStyle: "normal",
  //   fontWeight: "500",
  //   textTransform: "uppercase",
  //   textAlign: "center",
  //   marginLeft: 24,
  //   width: "100%",
  // },
  // phoneCallButton: {
  //   backgroundColor: "#7FC300",
  //   borderRadius: 8,
  //   padding: 10,
  //   paddingRight: 8,
  //   width: "127%",
  // },
  // phoneCallButtonText: {
  //   textAlign: "center",
  //   color: "#FFF",
  //   fontSize: 16,
  //   fontFamily: "Manrope",
  //   fontStyle: "normal",
  //   fontWeight: "600",
  //   textTransform: "uppercase",
  // },
  animationContainer: {
    width: "15%",
    height: "15%",
    marginLeft: 20,
  },
  buttonContainer: {
    paddingTop: 20,
  },
});

export default styles;
